# Generated by Django 4.2.19 on 2025-03-05 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Builder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact_info", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Current", "Current"),
                            ("Past", "Past"),
                            ("Pending", "Pending"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("subcontractor_count", models.IntegerField(default=0)),
                ("boom_lift_count", models.IntegerField(default=0)),
                ("builder_count", models.IntegerField(default=0)),
                ("site_count", models.IntegerField(default=0)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="companies", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Completed", "Completed"),
                            ("Planned", "Planned"),
                        ],
                        default="Planned",
                        max_length=50,
                    ),
                ),
                (
                    "builder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sites",
                        to="contractor.builder",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="contractor.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="builder",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="builders",
                to="contractor.company",
            ),
        ),
        migrations.CreateModel(
            name="BoomLift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boom_lift_id", models.CharField(max_length=100, unique=True)),
                ("subcontractor", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("hours", models.FloatField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("Planning", "Planning"),
                            ("Active", "Active"),
                            ("Completed", "Completed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("oil_change", models.BooleanField(default=False)),
                (
                    "oil_change_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("annual_inspection", models.BooleanField(default=False)),
                (
                    "annual_inspection_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("ndt", models.BooleanField(default=False)),
                (
                    "ndt_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("radiator_change", models.BooleanField(default=False)),
                (
                    "radiator_change_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("other_maintenance", models.TextField(blank=True, null=True)),
                (
                    "other_maintenance_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "builder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boom_lifts",
                        to="contractor.builder",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boom_lifts",
                        to="contractor.company",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boom_lifts",
                        to="contractor.site",
                    ),
                ),
            ],
        ),
    ]
