# Generated by Django 4.2.19 on 2025-03-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contractor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boomlift",
            name="gas_level",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="boomlift",
            name="oil_level",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="boomlift",
            name="boom_lift_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="boomlift",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boomlift",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boomlift",
            name="phase",
            field=models.CharField(
                choices=[
                    ("Planning", "Planning"),
                    ("Active", "Active"),
                    ("Completed", "Completed"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boomlift",
            unique_together={("boom_lift_id", "date")},
        ),
    ]
