# Generated by Django 4.2.19 on 2025-03-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contractor", "0002_boomlift_gas_level_boomlift_oil_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boomlift",
            name="builder",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="boomlift",
            name="site",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
