# Generated by Django 4.2.19 on 2025-03-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contractor", "0003_alter_boomlift_builder_alter_boomlift_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boomlift",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
