# Generated by Django 4.2.19 on 2025-03-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contractor", "0004_alter_boomlift_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="boomlift",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="boomlift",
            name="date",
            field=models.DateField(),
        ),
    ]
